import { Partner } from '@/types';

export const DEFAULT_PARTNERS: Partner[] = [
  {
    id: '1',
    name: 'Heritage Spa',
    category: 'Wellness',
    zone: 'Medina - Bab Doukkala',
    address: '40 Arset Aouzal, Bab Doukkala',
    phone: '+212 524 38 43 33',
    whatsapp: '+212 664 00 58 05',
    email: 'info@heritagespamarrakech.com',
    website: 'heritagespamarrakech.com',
    instagram: '@heritagespamarrakech',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: '3 emplacements. Demander le gerant.',
    tier: 'B',
    prixPublic: '250-400',
    payoutMAD: '150-240',
    payoutPct: '60%',
    priority: 'HAUTE',
    pitchAngle: 'Volume incremental — touristes qui n\'auraient jamais trouvé votre hammam seuls',
    objection: 'Discount trop élevé',
    reponse: 'On ajuste le payout ou on limite le volume. On achète de la demande incrémentale, pas vos clients plein tarif.',
    followup: '',
  },
  {
    id: '2',
    name: 'Les Bains de Marrakech',
    category: 'Wellness',
    zone: 'Medina - Kasbah',
    address: '2 Derb Sedra, Bab Agnaou',
    phone: '+212 524 38 14 28',
    whatsapp: '+212 651 17 19 10',
    email: 'contact@lesbainsdemarrakech.com',
    website: 'lesbainsdemarrakech.com',
    instagram: '@lesbainsdemarrakech',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: '20+ ans. Renove 2021. TripAdvisor Top 10%.',
    tier: 'A',
    prixPublic: '400-600',
    payoutMAD: '280-420',
    payoutPct: '70%',
    priority: 'HAUTE',
    pitchAngle: 'Institution premium — placement vedette dans nos packs Wellness. Votre réputation vend le pass.',
    objection: 'On ne veut pas de clients discount',
    reponse: 'On vous positionne premium. Vous limitez la disponibilité, featured placement, pas de bradage.',
    followup: '',
  },
  {
    id: '3',
    name: 'Le Bain de Kasbah',
    category: 'Wellness',
    zone: 'Medina - Kasbah',
    address: 'Derb El Hammam, Kasbah, pres Tombeaux Saadiens',
    phone: '+212 668 13 05 77',
    whatsapp: '+212 668 13 05 77',
    email: 'lebaindekasbah@gmail.com',
    website: 'lebaindekasbah.com',
    instagram: '',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: 'Independant. Proprio accessible. Ferme dimanche.',
    tier: 'C',
    prixPublic: '200-350',
    payoutMAD: '120-210',
    payoutPct: '60%',
    priority: 'MOYENNE',
    pitchAngle: 'Indépendant accessible — 10 min setup, revenu passif, zéro admin',
    objection: 'Trop petit pour nous',
    reponse: 'C\'est justement l\'avantage : décision rapide, pas de bureaucratie. Et on vous met en avant dans l\'app.',
    followup: '',
  },
  {
    id: '4',
    name: 'La Maison Arabe - Cooking',
    category: 'Food & Culinary',
    zone: 'Medina - Bab Doukkala',
    address: '1 Derb Assehbe, Bab Doukkala',
    phone: '+212 524 38 70 10',
    whatsapp: '',
    email: 'reservation@lamaisonarabe.com',
    website: 'lamaisonarabe.com',
    instagram: '@lamaisonarabe',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: 'Contact Yomna Younssi (Cooking Manager). Cours 1h et 3h.',
    tier: 'B',
    prixPublic: '400-700',
    payoutMAD: '240-420',
    payoutPct: '60%',
    priority: 'HAUTE',
    pitchAngle: 'Co-création — vous nous aidez à designer le cours idéal pour les pass holders',
    objection: 'Charge opérationnelle',
    reponse: 'Juste un scan QR. Si réservation nécessaire, on utilise des créneaux horaires.',
    followup: '',
  },
  {
    id: '5',
    name: 'Chef Tarik',
    category: 'Food & Culinary',
    zone: 'Route de Fes (Km 12)',
    address: 'Route de Fes (Km 12) / Medina',
    phone: '+212 661 14 85 14',
    whatsapp: '+212 661 14 85 14',
    email: 'contact@cheftarik.com',
    website: 'cheftarik.com',
    instagram: '@cheftarikmarrakech',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: 'Petit operateur. WhatsApp = meme numero. Decision rapide.',
    tier: 'C',
    prixPublic: '200-400',
    payoutMAD: '120-240',
    payoutPct: '60%',
    priority: 'MOYENNE',
    pitchAngle: 'Décision rapide — petit opérateur, WhatsApp direct, on signe en 10 min',
    objection: 'Volume incertain',
    reponse: 'Pilote 30 jours, zéro risque. Vous pausez quand vous voulez.',
    followup: '',
  },
  {
    id: '6',
    name: 'Marrakech Food Tours',
    category: 'Food & Culinary',
    zone: 'Medina',
    address: 'Points de RDV variables - Medina',
    phone: '+212 661 18 41 94',
    whatsapp: '',
    email: 'info@marrakechfoodtours.com',
    website: 'marrakechfoodtours.com',
    instagram: '@marrakechfoodtours',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: 'Tour operator = volume-dependant.',
    tier: 'B',
    prixPublic: '300-500',
    payoutMAD: '180-300',
    payoutPct: '60%',
    priority: 'MOYENNE',
    pitchAngle: 'Volume-dépendant — on vous apporte des groupes réguliers via les packs',
    objection: 'Logistique des groupes',
    reponse: 'On gère les créneaux côté app. Vous recevez des réservations confirmées.',
    followup: '',
  },
  {
    id: '7',
    name: 'Marrakech Quad Evasion',
    category: 'Adventure',
    zone: 'Route de Casablanca',
    address: 'Route de Casablanca / Route de Fes',
    phone: '+212 661 15 77 14',
    whatsapp: '+212 673 332 267',
    email: 'contact@marrakech-quad-evasion.com',
    website: 'marrakech-quad-evasion.com',
    instagram: '@marrakechquadevasion',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: 'Grosses marges. Chaque rider = profit pur.',
    tier: 'A',
    prixPublic: '350-800',
    payoutMAD: '280-560',
    payoutPct: '70%',
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Marges élevées — chaque rider = profit pur. AyaPass remplit vos créneaux vides.',
    objection: 'On a déjà nos propres canaux',
    reponse: 'AyaPass est un canal EN PLUS. Vos canaux existants restent intacts. C\'est du revenu additionnel.',
    followup: '',
  },
  {
    id: '8',
    name: 'Dunes & Desert',
    category: 'Adventure',
    zone: 'Gueliz (bureau)',
    address: 'Ouled Mansour (Office) / Gueliz',
    phone: '+212 524 35 41 41',
    whatsapp: '+212 661 53 96 39',
    email: 'info@dunesdeserts.com',
    website: 'dunesdeserts.com',
    instagram: '@dunesdesert',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: 'Bureau a Gueliz. Camel rides + desert.',
    tier: 'B',
    prixPublic: '400-800',
    payoutMAD: '240-480',
    payoutPct: '60%',
    priority: 'HAUTE',
    pitchAngle: 'Diversification — camel + desert sunset, on vous met dans les packs Adventure',
    objection: 'Saisonnalité',
    reponse: 'C\'est exactement pourquoi — on vous apporte du volume basse saison via les hôtels/riads.',
    followup: '',
  },
  {
    id: '9',
    name: 'Agafay Desert Luxury Camp',
    category: 'Adventure',
    zone: 'Agafay (~30km)',
    address: 'Agafay Desert',
    phone: '+212 661 92 09 20',
    whatsapp: '+212 617 704 440',
    email: 'contact@agafaydesertluxurycamp.com',
    website: 'agafaydesertluxurycamp.com',
    instagram: '@agafaydesertluxurycamp',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: 'Experience soiree/nuit. Segment premium.',
    tier: 'A',
    prixPublic: '800-2000',
    payoutMAD: '560-1400',
    payoutPct: '70%',
    priority: 'MOYENNE',
    pitchAngle: 'Segment premium — experience soirée/nuit, placement dans le pack "Luxury Marrakech"',
    objection: 'On est premium, pas discount',
    reponse: 'Justement : featured placement, pas de volume de masse. On envoie 2-3 clients/semaine max, pas 50.',
    followup: '',
  },
  {
    id: '10',
    name: 'Fantasia Chez Ali',
    category: 'Entertainment',
    zone: 'Route de Casablanca',
    address: 'Route de Casablanca',
    phone: '+212 524 30 77 30',
    whatsapp: '+212 764 960 256',
    email: 'info@chezali.ma',
    website: 'chezali.ma',
    instagram: '@chezali_fantasia',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: 'Spectacle + diner. 100+ couverts/soir.',
    tier: 'B',
    prixPublic: '400-800',
    payoutMAD: '240-480',
    payoutPct: '60%',
    priority: 'HAUTE',
    pitchAngle: 'Spectacle + dîner = ancre du pack soirée. Les touristes achètent le pass POUR ça.',
    objection: 'Nos prix sont fixes',
    reponse: 'On ne touche pas à vos prix affichés. Le payout est fixe par scan, pas une commission sur votre prix.',
    followup: '',
  },
  {
    id: '11',
    name: 'Comptoir Darna',
    category: 'Entertainment',
    zone: 'Hivernage',
    address: 'Avenue Echouhada, Hivernage',
    phone: '+212 524 43 77 02',
    whatsapp: '',
    email: 'contact@comptoirdarna.com',
    website: 'comptoirdarna.com',
    instagram: '@comptoirdarna',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: 'Institution depuis 1999. Restaurant + spectacle.',
    tier: 'B',
    prixPublic: '400-700',
    payoutMAD: '240-420',
    payoutPct: '60%',
    priority: 'HAUTE',
    pitchAngle: 'Institution depuis 1999 — crédibilité qui vend le pass. Placement vedette.',
    objection: 'Image de marque',
    reponse: 'AyaPass = curation premium, pas Groupon. Vous contrôlez la dispo et le volume.',
    followup: '',
  },
  {
    id: '12',
    name: 'ANIMA Garden',
    category: 'Gardens',
    zone: 'Ourika (Km 28)',
    address: 'Douar Sbiti, Km 28 Route d\'Ourika',
    phone: '+212 524 48 20 22',
    whatsapp: '',
    email: 'info@anima-garden.com',
    website: 'anima-garden.com',
    instagram: '@animagarden',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: 'Jardin Andre Heller. Prive. Oriente touristes.',
    tier: 'A',
    prixPublic: '70-120',
    payoutMAD: '50-84',
    payoutPct: '70%',
    priority: 'HAUTE',
    pitchAngle: 'Jardin privé unique — ancre du pack Nature. Chaque touriste veut y aller.',
    objection: 'On vend déjà nos propres billets',
    reponse: 'On ne remplace pas vos ventes directes — on ajoute des visiteurs qui ont un pass et cherchent quoi faire.',
    followup: '',
  },
  {
    id: '13',
    name: 'Le Jardin Secret',
    category: 'Gardens',
    zone: 'Medina - Mouassine',
    address: '121 Rue Mouassine',
    phone: '+212 524 39 00 40',
    whatsapp: '+212 667 813 868',
    email: 'info@lejardinsecretmarrakech.com',
    website: 'lejardinsecretmarrakech.com',
    instagram: '@lejardinsecret_marrakech',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: 'Gestion privee. Vend deja des billets.',
    tier: 'A',
    prixPublic: '80-120',
    payoutMAD: '56-84',
    payoutPct: '70%',
    priority: 'TRÈS HAUTE',
    pitchAngle: 'En pleine Médina, flux piéton massif. Ancre culture/nature dans tous les packs.',
    objection: 'Gestion privée, process strict',
    reponse: 'On s\'adapte à vos règles. Scan QR = 1 entrée, nominatif, pas de revente.',
    followup: '',
  },
  {
    id: '14',
    name: 'Amal Women\'s Training',
    category: 'Social Impact',
    zone: 'Gueliz',
    address: 'Rue Allal Ben Ahmed, Gueliz',
    phone: '+212 524 44 68 96',
    whatsapp: '+212 666 463 095',
    email: 'amalnonprofit@gmail.com',
    website: 'amalnonprofit.org',
    instagram: '@amalnonprofit',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: 'Entreprise sociale. Super angle PR.',
    tier: 'C',
    prixPublic: '80-150',
    payoutMAD: '48-90',
    payoutPct: '60%',
    priority: 'MOYENNE',
    pitchAngle: 'Super angle PR — impact social = différenciation pour AyaPass et storytelling puissant',
    objection: 'On est une association',
    reponse: 'Le modèle vous apporte des revenus prévisibles mensuels. Et on raconte votre histoire dans l\'app.',
    followup: '',
  },
  {
    id: '15',
    name: 'Oasiria Water Park',
    category: 'Family',
    zone: 'Route d\'Amizmiz (Km 4)',
    address: 'Km 4, Route d\'Amizmiz',
    phone: '+212 524 38 04 38',
    whatsapp: '+212 620 049 784',
    email: 'info@oasiria.com',
    website: 'oasiria.com',
    instagram: '@oasiriamarrakech',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: 'Grand parc. Saisonnier = besoin trafic basse saison.',
    tier: 'B',
    prixPublic: '150-300',
    payoutMAD: '90-180',
    payoutPct: '60%',
    priority: 'BASSE',
    pitchAngle: 'Segment famille — parc aquatique = ancre du pack Family. Besoin trafic basse saison.',
    objection: 'Saisonnalité forte',
    reponse: 'AyaPass est actif toute l\'année. On vous apporte du volume quand vous en avez le plus besoin.',
    followup: '',
  },
];

export const PIPELINE_STAGES: string[] = [
  'À contacter',
  'WhatsApp envoyé',
  'RDV pris',
  'Visite faite',
  'Signé',
  'Refusé',
];

export const ROUTE_DAYS = [
  {
    jour: 'Jour 1',
    title: 'Médina Centre (Bab Doukkala + Mouassine + Kasbah)',
    partnerIds: ['13', '1', '3', '5'],
  },
  {
    jour: 'Jour 2',
    title: 'Médina + Gueliz',
    partnerIds: ['2', '4', '6', '14'],
  },
  {
    jour: 'Jour 3',
    title: 'Gueliz + Route Casablanca + Hivernage',
    partnerIds: ['11', '7', '8'],
  },
  {
    jour: 'Jour 4',
    title: 'Hors Centre',
    partnerIds: ['10', '12', '9', '15'],
  },
];

export const PRICING_TIERS = [
  {
    tier: 'A',
    name: 'Ancres',
    definition: 'Expériences iconiques, raison d\'achat du pass',
    payout: '70% du prix public',
    examples: 'Le Jardin Secret, ANIMA, Agafay, Quad Evasion, Les Bains',
  },
  {
    tier: 'B',
    name: 'Standards',
    definition: 'Bonnes expériences, demande régulière',
    payout: '60% du prix public',
    examples: 'Heritage Spa, Chez Ali, Dunes & Desert, Comptoir Darna, Oasiria',
  },
  {
    tier: 'C',
    name: 'Pépites',
    definition: 'Peu connues, besoin de visibilité',
    payout: '60% (marge effective plus haute)',
    examples: 'Le Bain de Kasbah, Chef Tarik, Amal',
  },
];
