import { Partner } from '@/types';

export const DEFAULT_PARTNERS: Partner[] = [
  {
    id: '1',
    name: 'Le Jardin Secret',
    category: 'Gardens',
    zone: 'Mouassine, Médina',
    address: '121 Rue Mouassine, Médina',
    phone: '+212 524 390 040',
    whatsapp: '+212 524 390 040',
    email: 'info@lejardinsecretmarrakech.com',
    website: 'https://lejardinsecretmarrakech.com',
    instagram: '@lejardinsecret',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: '',
    tier: 'A',
    prixPublic: 80,
    payoutMAD: 40,
    payoutPct: 50,
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Flux touristique garanti — AyaPass envoie des visiteurs qualifiés directement',
    objection: 'Déjà assez de visiteurs',
    reponse: 'AyaPass amène un segment premium supplémentaire — pas de cannibalisation, que du bonus',
    followup: '',
  },
  {
    id: '2',
    name: 'Heritage Spa',
    category: 'Wellness',
    zone: 'Bab Doukkala, Médina',
    address: '40 Arset Aouzal, Bab Doukkala',
    phone: '+212 524 384 333',
    whatsapp: '+212 524 384 333',
    email: 'info@heritagespamarrakech.com',
    website: 'https://heritagespamarrakech.com',
    instagram: '@heritagespa',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 250,
    payoutMAD: 75,
    payoutPct: 30,
    priority: 'HAUTE',
    pitchAngle: 'Visibilité premium auprès des touristes — canal d\'acquisition zéro effort',
    objection: 'Commission trop basse',
    reponse: 'C\'est un client que vous n\'auriez pas eu autrement — 100% incrémental',
    followup: '',
  },
  {
    id: '3',
    name: 'Le Bain de Kasbah',
    category: 'Wellness',
    zone: 'Kasbah, Médina',
    address: 'Derb El Hammam, Kasbah',
    phone: '+212 661 234 567',
    whatsapp: '+212 661 234 567',
    email: 'contact@baindekasbah.com',
    website: 'https://baindekasbah.com',
    instagram: '@baindekasbah',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: '',
    tier: 'C',
    prixPublic: 200,
    payoutMAD: 50,
    payoutPct: 25,
    priority: 'MOYENNE',
    pitchAngle: 'Positionnement authentique Kasbah — AyaPass attire les amateurs de culture',
    objection: 'Pas besoin de partenaires',
    reponse: 'Aucun engagement — vous ne payez que quand un client AyaPass vient',
    followup: '',
  },
  {
    id: '4',
    name: 'Chef Tarik',
    category: 'Food',
    zone: 'Route de Fes',
    address: 'Route de Fes Km 12',
    phone: '+212 662 345 678',
    whatsapp: '+212 662 345 678',
    email: 'contact@cheftarik.com',
    website: 'https://cheftarik.com',
    instagram: '@cheftarik',
    jourVisite: 'Jour 1',
    status: 'À contacter',
    notes: '',
    tier: 'C',
    prixPublic: 350,
    payoutMAD: 88,
    payoutPct: 25,
    priority: 'MOYENNE',
    pitchAngle: 'Expérience culinaire exclusive — AyaPass positionne le chef comme incontournable',
    objection: 'Trop loin du centre',
    reponse: 'Les touristes AyaPass cherchent justement l\'authenticité hors sentiers battus',
    followup: '',
  },
  {
    id: '5',
    name: 'Les Bains de Marrakech',
    category: 'Wellness',
    zone: 'Bab Agnaou, Médina',
    address: '2 Derb Sedra, Bab Agnaou',
    phone: '+212 524 381 428',
    whatsapp: '+212 524 381 428',
    email: 'info@lesbainsdemarrakech.com',
    website: 'https://lesbainsdemarrakech.com',
    instagram: '@lesbainsdemarrakech',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: '',
    tier: 'A',
    prixPublic: 400,
    payoutMAD: 120,
    payoutPct: 30,
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Spa iconique — AyaPass renforce le positionnement haut de gamme',
    objection: 'Image de marque à protéger',
    reponse: 'AyaPass est un pass premium, pas un deal discount — vos standards sont respectés',
    followup: '',
  },
  {
    id: '6',
    name: 'La Maison Arabe Cooking',
    category: 'Food',
    zone: 'Bab Doukkala, Médina',
    address: '1 Derb Assehbe, Bab Doukkala',
    phone: '+212 524 387 010',
    whatsapp: '+212 524 387 010',
    email: 'restaurant@lamaisonarabe.com',
    website: 'https://lamaisonarabe.com',
    instagram: '@lamaisonarabe',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 500,
    payoutMAD: 125,
    payoutPct: 25,
    priority: 'HAUTE',
    pitchAngle: 'Cours de cuisine légendaire — AyaPass amène les foodies directement',
    objection: 'Déjà complet souvent',
    reponse: 'On remplit vos créneaux creux — vous choisissez les disponibilités',
    followup: '',
  },
  {
    id: '7',
    name: 'Marrakech Food Tours',
    category: 'Food',
    zone: 'Médina',
    address: 'Point de départ Médina',
    phone: '+212 663 456 789',
    whatsapp: '+212 663 456 789',
    email: 'hello@marrakechfoodtours.com',
    website: 'https://marrakechfoodtours.com',
    instagram: '@marrakechfoodtours',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 350,
    payoutMAD: 88,
    payoutPct: 25,
    priority: 'HAUTE',
    pitchAngle: 'Food tours = expérience #1 demandée — AyaPass booste la découvrabilité',
    objection: 'On a déjà nos canaux',
    reponse: 'AyaPass est complémentaire — un canal en plus, zéro coût fixe',
    followup: '',
  },
  {
    id: '8',
    name: 'Amal Women\'s Training',
    category: 'Social Impact',
    zone: 'Gueliz',
    address: 'Rue Allal Ben Ahmed, Gueliz',
    phone: '+212 524 446 896',
    whatsapp: '+212 524 446 896',
    email: 'info@amalnonprofit.org',
    website: 'https://amalnonprofit.org',
    instagram: '@amalmarrakech',
    jourVisite: 'Jour 2',
    status: 'À contacter',
    notes: '',
    tier: 'C',
    prixPublic: 150,
    payoutMAD: 30,
    payoutPct: 20,
    priority: 'HAUTE',
    pitchAngle: 'Impact social + gastronomie — les touristes adorent les causes qui comptent',
    objection: 'On est une association',
    reponse: 'Justement — AyaPass vous apporte des revenus supplémentaires pour votre mission',
    followup: '',
  },
  {
    id: '9',
    name: 'Comptoir Darna',
    category: 'Entertainment',
    zone: 'Hivernage',
    address: 'Avenue Echouhada, Hivernage',
    phone: '+212 524 437 702',
    whatsapp: '+212 524 437 702',
    email: 'info@comptoirdarna.com',
    website: 'https://comptoirdarna.com',
    instagram: '@comptoirdarna',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 300,
    payoutMAD: 75,
    payoutPct: 25,
    priority: 'HAUTE',
    pitchAngle: 'Soirée spectacle iconique — AyaPass positionne Comptoir comme LE spot nightlife',
    objection: 'On est déjà connu',
    reponse: 'Les touristes nouveaux ne connaissent pas encore — AyaPass les guide vers vous',
    followup: '',
  },
  {
    id: '10',
    name: 'Marrakech Quad Evasion',
    category: 'Adventure',
    zone: 'Route de Casablanca',
    address: 'Route de Casablanca, Km 8',
    phone: '+212 664 567 890',
    whatsapp: '+212 664 567 890',
    email: 'info@marrakechquad.com',
    website: 'https://marrakechquad.com',
    instagram: '@marrakechquad',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: '',
    tier: 'A',
    prixPublic: 450,
    payoutMAD: 135,
    payoutPct: 30,
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Aventure désert = gros ticket moyen — AyaPass convertit les aventuriers',
    objection: 'Logistique complexe',
    reponse: 'Zéro logistique côté partenaire — on gère la vente, vous gérez l\'expérience',
    followup: '',
  },
  {
    id: '11',
    name: 'Dunes & Desert',
    category: 'Adventure',
    zone: 'Gueliz',
    address: 'Bureau Gueliz, Marrakech',
    phone: '+212 665 678 901',
    whatsapp: '+212 665 678 901',
    email: 'book@dunesanddesert.com',
    website: 'https://dunesanddesert.com',
    instagram: '@dunesanddesert',
    jourVisite: 'Jour 3',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 600,
    payoutMAD: 150,
    payoutPct: 25,
    priority: 'HAUTE',
    pitchAngle: 'Excursions désert premium — AyaPass est le canal parfait pour les aventuriers',
    objection: 'Prix déjà serrés',
    reponse: 'On ne négocie pas vos prix — on amène des clients au tarif affiché',
    followup: '',
  },
  {
    id: '12',
    name: 'Fantasia Chez Ali',
    category: 'Entertainment',
    zone: 'Route de Casablanca',
    address: 'Route de Casablanca, Km 10',
    phone: '+212 524 307 730',
    whatsapp: '+212 524 307 730',
    email: 'info@chezali.com',
    website: 'https://chezali.com',
    instagram: '@chezali',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: '',
    tier: 'B',
    prixPublic: 350,
    payoutMAD: 88,
    payoutPct: 25,
    priority: 'HAUTE',
    pitchAngle: 'Spectacle fantasia mythique — AyaPass cible les familles et groupes',
    objection: 'On travaille avec les agences',
    reponse: 'AyaPass complète les agences — on touche les voyageurs indépendants',
    followup: '',
  },
  {
    id: '13',
    name: 'ANIMA Garden',
    category: 'Gardens',
    zone: 'Route de l\'Ourika',
    address: 'Douar Sbiti, Route de l\'Ourika Km 27',
    phone: '+212 524 482 695',
    whatsapp: '+212 524 482 695',
    email: 'info@anima-garden.com',
    website: 'https://anima-garden.com',
    instagram: '@animagarden',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: '',
    tier: 'A',
    prixPublic: 120,
    payoutMAD: 48,
    payoutPct: 40,
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Jardin unique d\'André Heller — AyaPass amène les amateurs d\'art et nature',
    objection: 'On préfère garder le contrôle',
    reponse: 'Vous gardez 100% du contrôle — AyaPass est juste un canal de plus',
    followup: '',
  },
  {
    id: '14',
    name: 'Cactus Thiemann',
    category: 'Adventure',
    zone: 'Route de l\'Ourika',
    address: 'Route de l\'Ourika, Km 22',
    phone: '+212 666 789 012',
    whatsapp: '+212 666 789 012',
    email: 'info@cactusthiemann.com',
    website: 'https://cactusthiemann.com',
    instagram: '@cactusthiemann',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: '',
    tier: 'C',
    prixPublic: 80,
    payoutMAD: 24,
    payoutPct: 30,
    priority: 'MOYENNE',
    pitchAngle: 'Jardin de cactus unique — combo parfait avec ANIMA pour la route Ourika',
    objection: 'Trop petit pour un partenariat',
    reponse: 'AyaPass s\'adapte à toutes les tailles — même les petites structures en profitent',
    followup: '',
  },
  {
    id: '15',
    name: 'Palooza Land',
    category: 'Family',
    zone: 'Route de l\'Ourika',
    address: 'Route de l\'Ourika, Km 15',
    phone: '+212 667 890 123',
    whatsapp: '+212 667 890 123',
    email: 'info@paloozaland.com',
    website: 'https://paloozaland.com',
    instagram: '@paloozaland',
    jourVisite: 'Jour 4',
    status: 'À contacter',
    notes: '',
    tier: 'A',
    prixPublic: 200,
    payoutMAD: 60,
    payoutPct: 30,
    priority: 'TRÈS HAUTE',
    pitchAngle: 'Parc familial — AyaPass cible les familles en vacances, gros volume',
    objection: 'On cible les locaux',
    reponse: 'Les touristes avec enfants cherchent exactement ça — nouveau segment pour vous',
    followup: '',
  },
];

export const PIPELINE_STAGES: string[] = [
  'À contacter',
  'WhatsApp envoyé',
  'RDV pris',
  'Visite faite',
  'Signé',
  'Refusé',
];

export const ROUTE_DAYS = [
  {
    jour: 'Jour 1',
    title: 'Médina Centre (Bab Doukkala + Mouassine + Kasbah)',
    partnerIds: ['1', '2', '3', '4'],
  },
  {
    jour: 'Jour 2',
    title: 'Médina + Gueliz',
    partnerIds: ['5', '6', '7', '8'],
  },
  {
    jour: 'Jour 3',
    title: 'Gueliz + Route Casablanca + Hivernage',
    partnerIds: ['9', '10', '11'],
  },
  {
    jour: 'Jour 4',
    title: 'Hors Centre (Route Ourika + Route Casablanca)',
    partnerIds: ['12', '13', '14', '15'],
  },
];
